name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: npm install and npm run build
        run: |
          npm i
          npm run build:prod
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./docs/ s3://bookrage001.com --delete


    # - uses: Bookrage001/bookrage001.github.io@master
    #   with:
    #     args: --acl public-read --follow-symlinks --delete
    #   env:
    #     AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     AWS_REGION: 'ap-southeast-2'   # optional: defaults to us-east-1
    #     SOURCE_DIR: 'public'      # optional: defaults to entire repository

      # - name: All things angular
      #   uses: bookrage001/bookrage001.github.io ## replace by latest version without it you will see Expected format {org}/{repo}[/path]@ref. Actual 'AhsanAyaz/angular-deploy-gh-pages-actions',Input string was not in a correct format.
      #   with:
      #     github_access_token: ${{ secrets.ACCESS_TOKEN }} # see the Configuration section for how you can create secrets
      #     build_configuration: staging # The build environment for the app. please look configurations in your angular.json
      #     base_href: /   # make sure this corresponds to https://<your_username>.github.io/<base_href>/
      #     deploy_branch: gh-pages # The branch the action should deploy to.
      #     angular_dist_build_folder: dist/my-project # The folder where your project is supposed to be after running ng build by the action.
